#!/usr/bin/env bash

rm -rf htmlcov/*
echo "Starting coverage tests"
coverage run -m pytest tests/
echo "Starting coverage report"
coverage report
echo "Starting coverage html"
coverage html

echo "Serving coverage report..."
cd htmlcov/
python -m http.server 8000