name: "Test"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: "actions/checkout@v4.2.2"

      - name: "Set up Python"
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements_test.txt

      - name: Run Tests
        run: |
          pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            -n auto \
            -o console_output_style=count \
            -p no:sugar \
            tests

      - name: Coverage
        run: |
          coverage run -m pytest tests/
          coverage report

      - name: Generate HTML Coverage Report
        run: coverage html
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./htmlcov